version: "3"
services:
  dev:  
    image: node:11
    volumes:
      - ./:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm start"
    links:
      - mongo
      - redis
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
     - "8123:6379"