version: "3"
services:
  dev:  
    image: node:12
    volumes:
      - ./:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run app"
    links:
      - mongo
      - redis
    ports:
      - "3000:3000"
      - "9229:9229"
  mongo:
    container_name: cloud-auth-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: cloud-auth-redis
    ports:
     - "8123:6379"
     
