version: '3'
services:
  authservice:
    container_name: authservice
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
  redis:
    image: redis
    container_name: redis
